language: go

go:
  - "1.9.x"
  - "1.10.x"
  - "master"

script:
  - set -x
  - wget https://dist.ipfs.io/go-ipfs/v0.4.14/go-ipfs_v0.4.14_linux-amd64.tar.gz -O /tmp/go-ipfs.tar.gz
  - cd /tmp
  - tar xvfz go-ipfs.tar.gz
  - sudo cp go-ipfs/ipfs /usr/local/bin
  - ipfs version
  - make test
